admin:
    email: <outgoing-gmail-address>
    password: <email-account-password>
    email_subject: Your Amazing Conference
base_email:
    filename: base.html
    start_tag:
responses:
    accept:
        title:
        true_filename: accept.html
        false_filename: reject.html
        conditional: []
        conflict: []
        replacements:
            name:
                value: firstname
                params:
            response_link:
                value:
                params:
                    href: response_link
    travel:
        title: Travel Grant
        true_filename: travel_accepted.html
        false_filename: travel_rejected.html
        conditional: [travel_applied, accept]
        conflict: []
        replacements:
            bursary_name:
                value: bursary_name
                params:
            sponsor:
                value: sponsor
                params:
            response_link:
                value:
                params:
                    href: response_link
    talk:
        title: Talk
        true_filename: talk_accepted.html
        false_filename: talk_rejected.html
        conditional: [talk_applied, accept]
        conflict: []
        replacements:
            talk_length:
                value: talk_length
                params:
    poster:
        title: Poster
        true_filename: poster_accepted.html
        false_filename: poster_rejected.html
        conditional: [poster_applied, accept]
        conflict: []
        replacements:
    waitlist:
        title: Waitlist
        true_filename: waitlist.html
        false_filename:
        conditional: []
        conflict: [accept]
        replacements:
