admin:
    email: <outgoing-gmail-address>
    password: <email-account-password>
    email_subject: Your Amazing Conference
base_email:
    filename: base.html
    start_tag:
introduction:
    title:
    filename: introduction.html
    replace_tags: [name]
    replace_values: [firstname]
responses:
    accept:
        title: Application Response
        true_filename: accept.html
        false_filename: reject.html
        conditional: []
        conflict: []
        replace_tags: [profession]
        replace_values: [profession]
    travel:
        title: Travel Grant
        true_filename: travel_accepted.html
        false_filename: travel_rejected.html
        conditional: [travel_applied, accept]
        conflict: []
        replace_tags: [sponsor]
        replace_values: [sponsor]
    talk:
        title: Talk
        true_filename: talk_accepted.html
        false_filename: talk_rejected.html
        conditional: [talk_applied, accept]
        conflict: []
        replace_tags: [talk_length]
        replace_values: [talk_length]
    poster:
        title: Poster
        true_filename: poster_accepted.html
        false_filename: poster_rejected.html
        conditional: [poster_applied, accept]
        conflict: []
        replace_tags: []
        replace_values: []
